### ISSUE TITLE
GitHub hook LookupError: no exception for 204

### ISSUE THREAD

**Issue by RickyCook** [sprucedev/DockCI#362]
https://rollbar.com/Spruce/DockCI/items/20/

```

Traceback (most recent call last):
1
File "/code/python_env/lib/python3.4/site-packages/flask/app.py", line 1817 in wsgi_app [args] [locals]
	wsgi_app arguments:
0 	<class 'flask.app.Flask'>
1 	{'CONTENT_LENGTH': '5438', 'CONTENT_TYPE': 'application/json', 'HTTP_ACCEPT': '*/*', 'HTTP_CONNECTION': 'close', 'HTTP_HOST': 'demo.dock.ci', 'HTTP_USER_AGENT': 'GitHub-Hookshot/333881f', 'HTTP_X_GITHUB_DELIVERY': '0b659380-9c93-11e5-86a5-45d3bef4d506', 'HTTP_X_GITHUB_EVENT': 'push', 'HTTP_X_HUB_SIGNATURE': 'sha1=874bb1ed0d6da13d7b2eeeebf6a76389f00af934', 'HTTP_X_REAL_IP': '192.30.252.34', ...}
2 	<class 'method'>
	wsgi_app local variables:
ctx 	<class 'flask.ctx.RequestContext'>
e 	<class 'LookupError'>
environ 	{'CONTENT_LENGTH': '5438', 'CONTENT_TYPE': 'application/json', 'HTTP_ACCEPT': '*/*', 'HTTP_CONNECTION': 'close', 'HTTP_HOST': 'demo.dock.ci', 'HTTP_USER_AGENT': 'GitHub-Hookshot/333881f', 'HTTP_X_GITHUB_DELIVERY': '0b659380-9c93-11e5-86a5-45d3bef4d506', 'HTTP_X_GITHUB_EVENT': 'push', 'HTTP_X_HUB_SIGNATURE': 'sha1=874bb1ed0d6da13d7b2eeeebf6a76389f00af934', 'HTTP_X_REAL_IP': '192.30.252.34', ...}
error 	<class 'LookupError'>
self 	<class 'flask.app.Flask'>
start_response 	<class 'method'>
response = self.full_dispatch_request()
2
File "/code/python_env/lib/python3.4/site-packages/flask/app.py", line 1477 in full_dispatch_request [args] [locals]
	full_dispatch_request arguments:
0 	<class 'flask.app.Flask'>
	full_dispatch_request local variables:
rv 	None
self 	<class 'flask.app.Flask'>
rv = self.handle_user_exception(e)
3
File "/code/python_env/lib/python3.4/site-packages/flask_restful/__init__.py", line 270 in error_router [args] [locals]
	error_router arguments:
0 	<class 'flask_restful.Api'>
1 	<class 'method'>
2 	<class 'LookupError'>
	error_router local variables:
e 	<class 'LookupError'>
original_handler 	<class 'method'>
self 	<class 'flask_restful.Api'>
return original_handler(e)
4
File "/code/python_env/lib/python3.4/site-packages/flask/app.py", line 1381 in handle_user_exception [args] [locals]
	handle_user_exception arguments:
0 	<class 'flask.app.Flask'>
1 	<class 'LookupError'>
	handle_user_exception local variables:
app_handlers 	[]
blueprint_handlers 	[]
e 	<class 'LookupError'>
exc_type 	<class 'type'>
exc_value 	<class 'LookupError'>
handlers 	{}
self 	<class 'flask.app.Flask'>
tb 	<class 'traceback'>
reraise(exc_type, exc_value, tb)
5
File "/code/python_env/lib/python3.4/site-packages/flask/_compat.py", line 33 in reraise [args] [locals]
	reraise arguments:
0 	<class 'type'>
1 	<class 'LookupError'>
tb 	<class 'traceback'>
	reraise local variables:
tb 	<class 'traceback'>
tp 	<class 'type'>
value 	<class 'LookupError'>
raise value
6
File "/code/python_env/lib/python3.4/site-packages/flask/app.py", line 1475 in full_dispatch_request [args] [locals]
	full_dispatch_request arguments:
0 	<class 'flask.app.Flask'>
	full_dispatch_request local variables:
rv 	None
self 	<class 'flask.app.Flask'>
rv = self.dispatch_request()
7
File "/code/python_env/lib/python3.4/site-packages/flask/app.py", line 1461 in dispatch_request [args] [locals]
	dispatch_request arguments:
0 	<class 'flask.app.Flask'>
	dispatch_request local variables:
req 	<class 'flask.wrappers.Request'>
rule 	<class 'werkzeug.routing.Rule'>
self 	<class 'flask.app.Flask'>
return self.view_functions[rule.endpoint](**req.view_args)
8
File "/code/dockci/views/job.py", line 63 in job_new_view [args] [locals]
	job_new_view arguments:
0 	dockci
	job_new_view local variables:
has_event_header 	true
job 	<class 'dockci.models.job.Job'>
project 	<class 'dockci.models.project.Project'>
project_slug 	dockci
job_new_github(project, job)
9
File "/code/dockci/views/job.py", line 135 in job_new_github [args] [locals]
	job_new_github arguments:
0 	<class 'dockci.models.project.Project'>
1 	<class 'dockci.models.job.Job'>
	job_new_github local variables:
job 	<class 'dockci.models.job.Job'>
project 	<class 'dockci.models.project.Project'>
push_data 	{'after': '0000000000000000000000000000000000000000', 'base_ref': None, 'before': '3d642c3708958e7d6480c414e54f7b1647c47968', 'commits': [], 'compare': 'https://github.com/sprucedev/DockCI/compare/3d642c370895...000000000000', 'created': False, 'deleted': True, 'forced': True, 'head_commit': None, 'organization': {'avatar_url': 'https://avatars.githubusercontent.com/u/12792915?v=3', 'description': '', 'events_url': 'https://api.github.com/orgs/sprucedev/events', 'id': 12792915, 'login': 'sprucedev', 'members_url': 'https://api.github.com/orgs/sprucedev/members{/member}', 'public_members_url': 'https://api.github.com/orgs/sprucedev/public_members{/member}', 'repos_url': 'https://api.github.com/orgs/sprucedev/repos', 'url': 'https://api.github.com/orgs/sprucedev'}, ...}
job_new_abort(job, 204)
10
File "/code/dockci/views/job.py", line 90 in job_new_abort [args] [locals]
	job_new_abort arguments:
0 	<class 'dockci.models.job.Job'>
1 	204
message 	None
	job_new_abort local variables:
job 	<class 'dockci.models.job.Job'>
message 	None
status 	204
abort(status)
11
File "/code/python_env/lib/python3.4/site-packages/werkzeug/exceptions.py", line 645 in __call__ [args] [locals]
	__call__ arguments:
0 	<class 'werkzeug.exceptions.Aborter'>
1 	204
	__call__ local variables:
args 	[]
code 	204
kwargs 	{}
self 	<class 'werkzeug.exceptions.Aborter'>
raise LookupError('no exception for %r' % code)
LookupError: no exception for 204
```

**Comment by RickyCook** [comment]
Occurs when something is deleted. Should be fixed, but not right now.
